import { GitCommandFailedError } from '../errors/GitCommandFailedError';
import { mapWithConcurrency } from '../mapWithConcurrency';
import { refResolves } from '../refResolves';
import { runGit } from '../runGit';

const UNTRACKED_DIFF_CONCURRENCY = 8;

const UNTRACKED_FILE_DIFF_ARGS = [
  '--no-pager',
  'diff',
  '--no-index',
  '--no-color',
  '--no-ext-diff',
  '--no-textconv',
  '--',
  '/dev/null',
] as const;

export class GitCliDiffReader {
  async getUncommittedDiff(worktreePath: string): Promise<string> {
    await this.assertHeadExists(worktreePath);
    // `diff HEAD` covers staged + unstaged tracked paths. Untracked paths need
    // explicit /dev/null comparisons, generated by Git so modes, binary files,
    // quoting, and empty files keep standard unified-diff semantics.
    const [trackedDiff, untrackedPathsOutput] = await Promise.all([
      runGit(worktreePath, ['--no-pager', 'diff', '--no-color', 'HEAD']),
      runGit(worktreePath, ['ls-files', '--others', '--exclude-standard', '-z']),
    ]);
    const paths = this.parseUntrackedPaths(untrackedPathsOutput);

    if (paths.length === 0) {
      return trackedDiff;
    }

    return this.mergeTrackedAndUntrackedDiffs(worktreePath, trackedDiff, paths);
  }

  private parseUntrackedPaths(output: string): string[] {
    return output.split('\0').filter((path) => path.length > 0 && !path.endsWith('/'));
  }

  private async mergeTrackedAndUntrackedDiffs(
    worktreePath: string,
    trackedDiff: string,
    paths: string[]
  ): Promise<string> {
    const untrackedDiffs = await mapWithConcurrency(paths, UNTRACKED_DIFF_CONCURRENCY, (path) =>
      this.getUntrackedFileDiff(worktreePath, path)
    );
    return trackedDiff + untrackedDiffs.join('');
  }

  private getUntrackedFileDiff(worktreePath: string, path: string): Promise<string> {
    return runGit(worktreePath, [...UNTRACKED_FILE_DIFF_ARGS, path], { acceptedExitCodes: [1] });
  }

  /**
   * On an unborn HEAD (zero commits) `git diff HEAD` fails with a confusing
   * "ambiguous argument" error — detect it first and report clearly. Do not fake
   * an empty diff: there may be staged files, and an empty diff would lie.
   */
  private async assertHeadExists(worktreePath: string): Promise<void> {
    if (!(await refResolves(worktreePath, 'HEAD'))) {
      throw new GitCommandFailedError('Repository has no commits yet.');
    }
  }
}
